export const GET_ONE_STOCK_ENTRY_REQUEST = "GET_ONE_STOCK_ENTRY_REQUEST"
export const GET_ONE_STOCK_ENTRY_SUCCESS = "GET_ONE_STOCK_ENTRY_SUCCESS"
export const GET_ONE_STOCK_ENTRY_FAIL = "GET_ONE_STOCK_ENTRY_FAIL"

export const GET_STOCK_ENTRY_REQUEST = "GET_STOCK_ENTRY_REQUEST"
export const GET_STOCK_ENTRY_SUCCESS = "GET_STOCK_ENTRY_SUCCESS"
export const GET_STOCK_ENTRY_FAIL = "GET_STOCK_ENTRY_FAIL"

export const CREATE_STOCK_ENTRY_REQUEST = "CREATE_STOCK_ENTRY_REQUEST"
export const CREATE_STOCK_ENTRY_SUCCESS = "CREATE_STOCK_ENTRY_SUCCESS"
export const CREATE_STOCK_ENTRY_FAIL = "CREATE_STOCK_ENTRY_FAIL"

export const UPDATE_STOCK_ENTRY_REQUEST = "UPDATE_STOCK_ENTRY_REQUEST"
export const UPDATE_STOCK_ENTRY_SUCCESS = "UPDATE_STOCK_ENTRY_SUCCESS"
export const UPDATE_STOCK_ENTRY_FAIL = "UPDATE_STOCK_ENTRY_FAIL"

export const DELETE_STOCK_ENTRY_REQUEST = "DELETE_STOCK_ENTRY_REQUEST"
export const DELETE_STOCK_ENTRY_SUCCESS = "DELETE_STOCK_ENTRY_SUCCESS"
export const DELETE_STOCK_ENTRY_FAIL = "DELETE_STOCK_ENTRY_FAIL"
