export const GET_ONE_USER_ADDRESS_REQUEST = "GET_ONE_USER_ADDRESS_REQUEST"
export const GET_ONE_USER_ADDRESS_SUCCESS = "GET_ONE_USER_ADDRESS_SUCCESS"
export const GET_ONE_USER_ADDRESS_FAIL = "GET_ONE_USER_ADDRESS_FAIL"

export const GET_USER_ADDRESS_REQUEST = "GET_USER_ADDRESS_REQUEST"
export const GET_USER_ADDRESS_SUCCESS = "GET_USER_ADDRESS_SUCCESS"
export const GET_USER_ADDRESS_FAIL = "GET_USER_ADDRESS_FAIL"

export const CREATE_USER_ADDRESS_REQUEST = "CREATE_USER_ADDRESS_REQUEST"
export const CREATE_USER_ADDRESS_SUCCESS = "CREATE_USER_ADDRESS_SUCCESS"
export const CREATE_USER_ADDRESS_FAIL = "CREATE_USER_ADDRESS_FAIL"

export const UPDATE_USER_ADDRESS_REQUEST = "UPDATE_USER_ADDRESS_REQUEST"
export const UPDATE_USER_ADDRESS_SUCCESS = "UPDATE_USER_ADDRESS_SUCCESS"
export const UPDATE_USER_ADDRESS_FAIL = "UPDATE_USER_ADDRESS_FAIL"

export const DELETE_USER_ADDRESS_REQUEST = "DELETE_USER_ADDRESS_REQUEST"
export const DELETE_USER_ADDRESS_SUCCESS = "DELETE_USER_ADDRESS_SUCCESS"
export const DELETE_USER_ADDRESS_FAIL = "DELETE_USER_ADDRESS_FAIL"
